version: '2'
services:
    dalalserver:
        container_name: dalalstreet_server_1
        build: .
        volumes: 
            - $GOPATH:/go
            - ./:/go/src/github.com/delta/dalal-street-server
        ports:
            - "8000:8000"
        depends_on:
            - db
        env_file:
            - .env
        environment:
            MYSQL_DATABASE: ${DB_NAME}
            DALAL_ENV: Docker

    db:
        container_name: dalalstreet_db_1
        image: mysql:5.7
        volumes:
            - ./docker/mysql:/var/lib/mysql
        env_file:
            - .env
        ports:
            - "3307:3306"
        environment:
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_ROOT_PASSWORD: ${DB_PASS}
    
    phpmyadmin:
        container_name: dalalstreet_pma_1
        image: phpmyadmin/phpmyadmin
        env_file:
            - .env
        ports:
            - "9040:80"
        depends_on:
            - db
