version: '2'
services:
    web:
        container_name: dalalstreet_web_1
        image: nginx:latest
        volumes: 
            - ./docker/nginx:/etc/nginx/conf.d
            - ./frontend:/var/www/dalalstreet
        ports:
            - 9000:80
    
    dalalserver:
        container_name: dalalstreet_server_1
        build: .
        volumes: 
            - $GOPATH:/go
        ports:
            - 9020:3000
        depends_on:
            - db
        env_file:
            - .env
        environment:
            MYSQL_DATABASE: ${DB_NAME} 

    db:
        container_name: dalalstreet_db_1
        image: mysql:latest
        volumes:
            - ./docker/mysql:/var/lib/mysql
        env_file:
            - .env
        environment:
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_ROOT_PASSWORD: ${DB_PASS}
        ports:
            - 9006:3306
    
    phpmyadmin:
        container_name: dalalstreet_pma_1
        image: phpmyadmin/phpmyadmin
        env_file:
            - .env
        ports:
            - 9010:80
        depends_on:
            - db
