version: 2
jobs:
  build:
    working_directory: /go/src/github.com/delta/dalal-street-server
    docker:
      - image: circleci/golang:1.13
      - image: circleci/mysql:5.7

    steps:
      - checkout

      - run:
          name: Setup protobuf
          command: |
            wget -q https://github.com/google/protobuf/releases/download/v3.2.0rc2/protoc-3.2.0rc2-linux-x86_64.zip
            unzip -qq protoc-3.2.0rc2-linux-x86_64.zip
            cd ../
            go get -u github.com/golang/protobuf/{proto,protoc-gen-go}
            cd $GOPATH/src/github.com/golang/protobuf/protoc-gen-go/
            git reset --hard ed6926b37a637426117ccab59282c3839528a700
            go install github.com/golang/protobuf/protoc-gen-go

      - run:
          name: Install Go dependecies
          command: |
            cd ../
            go get -v github.com/gemnasium/migrate

      - run:
          name: Update submodules
          command: |
            git submodule init
            git submodule update --recursive

      - run:
          name: Run protobuf tests
          command: |
            export PATH=$PATH:$(pwd)/bin
            ./build_proto.sh

      - run:
          name: Setup MySQL
          command: |
            sudo apt-get update
            sudo apt install -y default-mysql-client
            mysql -h 127.0.0.1 -u root -e 'CREATE DATABASE dalalstreet_test;'
      
      - run:
          name: Run unit and integration tests
          command: |
            go get
            cp config.json.example config.json
            # ./test.sh
